name: "AI Code Reviewer"
description: "Automated code reviews using GPT-4"
inputs:
  GITHUB_TOKEN:
    description: "GitHub token"
    required: true
  OPENAI_API_KEY:
    description: "OpenAI API key"
    required: true
  OPENAI_API_MODEL:
    description: "OpenAI API model to use"
    required: true
    default: "gpt-4o-2024-11-20"
  exclude:
    description: "Comma-separated list of files to exclude from review"
    required: false
    default: ""
runs:
  using: "node16"
  main: "dist/index.js"
branding:
  icon: "aperture"
  color: "green"
